CREATE TABLE IF NOT EXISTS
   projects (
      id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
      `name` VARCHAR(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
   );

CREATE TABLE IF NOT EXISTS
   tasks (
      id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
      project_id INTEGER NOT NULL,
      `name` VARCHAR(255) NOT NULL,
      priority ENUM('none', 'low', 'medium', 'high') NOT NULL,
      duration INTEGER NOT NULL,
      due_date DATETIME,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
   );

CREATE TABLE IF NOT EXISTS
   notes (
      id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
      title VARCHAR(255) NOT NULL,
      `description` VARCHAR(5000) NOT NULL,
      color VARCHAR(30) NOT NULL,
      x INTEGER NOT NULL,
      y INTEGER NOT NULL,
      `size` VARCHAR(20) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
   );