name: CI

on:
   push:
      branches: ['**']
   pull_request:
      branches: ['**']

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repo
           uses: actions/checkout@v3

         - name: Use Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 18

         - name: Install dependencies
           run: npm ci

         - name: Run lint
           run: npm run lint

         - name: Run tests
           run: npm test -- --passWithNoTests

         - name: Build app
           run: npm run build
